### Create new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "111"
}

###Sign in user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "111"
}

### Get signed in user
GET http://localhost:3000/auth/whoami

### Sign out user
POST http://localhost:3000/auth/signout

### Find user by id
GET  http://localhost:3000/auth/2

### Find all users with this email
GET  http://localhost:3000/auth?email=test@test.com

### Delete user by id
DELETE http://localhost:3000/auth/12

### Update user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "defhuerhu"
}